version: "3"
services:
  orangotango-postgres:
    image: postgres:13.1
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "90:5432"
    volumes:
      - C:/Outros/postgres/data:/var/lib/postgresql/data 
    networks:
      - orangotango-network
      
  orangotango-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pg@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "91:80"
    depends_on:
      - orangotango-postgres
    networks:
      - orangotango-network

  orangotango-rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
    - "92:15672"
    - "93:5672"
    networks:
      - orangotango-network
  
networks:
  orangotango-network:
    driver: bridge