SELECT
	"DEALERSHIP"."NAME",
	"NUM_INSTALLATION",
	(CASE
		 WHEN "DEALERSHIP"."ID" = '3'  THEN 'E-mail'
		 ELSE  'Portal'
	END) AS TYPE
FROM
	"USER"
INNER JOIN "DEALERSHIP"
	ON "DEALERSHIP"."ID" = "USER"."ID_DEALERSHIP"
LEFT JOIN "CUSTOMER"
	ON "CUSTOMER"."ID" = "USER"."ID_CUSTOMER"
WHERE
	"USER"."STATUS"  = TRUE
	AND
	"DEALERSHIP"."USE_DOWNLOAD_ROBOT" = TRUE
	AND
	"CUSTOMER"."STANDARD_OPERATION" = TRUE
    AND
    "INVOICE"."STATUS" = TRUE
	AND
	"DEALERSHIP"."STATUS" = TRUE
ORDER BY	
	"DEALERSHIP"."NAME";