name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: use this action, test solution dir
      uses: zyborg/dotnet-tests-report@v1
      with:
        project_path: src\backend\6.Tests\Orangotango.Tests
        report_name: orangotango_tests
        report_title: Orangotango Tests
        github_token: ${{  e5e2fdaca9f3d97b53f0b4a8278412d1d6299d4d }}
