// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orangotango.Data.Context;

namespace Orangotango.Data.Migrations
{
    [DbContext(typeof(OrangotangoContext))]
    partial class OrangotangoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Orangotango.Business.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(128)")
                        .HasColumnName("Email");

                    b.Property<string>("FristName")
                        .HasColumnType("VARCHAR(128)")
                        .HasColumnName("FristName");

                    b.Property<string>("LastName")
                        .HasColumnType("VARCHAR(128)")
                        .HasColumnName("LastName");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NickName")
                        .HasColumnType("VARCHAR(128)")
                        .HasColumnName("NickName");

                    b.Property<string>("Password")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
