name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      CAMINHO_PROJETO_TESTES: .\src\backend\6.Tests\Orangotango.Tests\Orangotango.Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.2.20479.15

    - name: Executar testes automatizados
      run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity minimal
