name: WebApp

on:
  push:
    branches: [ master ]
    paths:
      - ./src/webapp
  pull_request:
    branches: [ master ]
    paths:
      - ./src/webapp
jobs:
  build:
  
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/webapp

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build
    - run: npm install
    - run: npm install -g @angular/cli > /dev/null
    - run: ng build --prod
